version: '3.4'

services:
  app:
      build:
        context: .
        dockerfile: ./.docker/php/Dockerfile
      image: php-container
      ports:
        - 8181:80
      volumes:
        - ./app:/srv/app
